# Database Settings
spring:
  datasource:
    #    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:tcp://localhost:9090/~/testdb
    url: jdbc:h2:tcp://localhost/mem:testdb
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password:
  jpa:
    #    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  # H2 Settings
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  activemq:
    broker-url:
      level: debug

  # logging
  logging:
    level:
      root: DEBUG
      org.springframework.web: DEBUG
      guru.springframework.controllers: DEBUG
      org.hibernate: DEBUG


liquibase:
  change-log:
    classpath: liquibase-changeLog.xml